/*
 * TipoGolpe.h
 *
 *  Created on: May 25, 2019
 *      Author: dev73
 */

#ifndef ENUMS_TIPO_GOLPE_H_
#define ENUMS_TIPO_GOLPE_H_

enum TIPO_GOLPE{NADA = 0, GOLPE_PINIA = 1 , GOLPE_PINION = 2, GOLPE_PATADA = 3, GOLPE_PATADON = 4,
	ACTIVAR_DEFENSA = 5, DESACTIVAR_DEFENSA = 6, GOLPE_ARROJAR =7, GOLPE_VOLAR =8,GOLPE_PODER =9,
	RECIBIR_DANIO = 10};

//	GOLPE_PINION_AGACHADO =7,GOLPE_PATADON_AGACHADO =8, GOLPE_PINIA_AGACHADO =9, GOLPE_ARROJAR =10,GOLPE_VOLAR =11,GOLPE_PODER =12};


#endif /* ENUMS_TIPO_GOLPE_H_ */
