/*
 * TipoGolpe.h
 *
 *  Created on: May 25, 2019
 *      Author: dev73
 */

#ifndef ENUMS_TIPO_GOLPE_H_
#define ENUMS_TIPO_GOLPE_H_

enum TIPO_GOLPE{NADA = 0, GOLPE_PINIA = 1 , GOLPE_PINION = 2, GOLPE_PATADA = 3, GOLPE_PATADON = 4, GOLPE_DEFENSA = 5,GOLPE_PATADA_AGACHADO =6,
	GOLPE_PINION_AGACHADO =7};

#endif /* ENUMS_TIPO_GOLPE_H_ */
